services:

  pagopa-selfcare-backoffice-scheduler:
    container_name: pagopa-selfcare-backoffice-scheduler
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8400:8080"
    networks:
      - pagopa-selfcare-backoffice-scheduler-net

networks:
  pagopa-selfcare-backoffice-scheduler-net:
    driver: bridge